# $XDG_CONFIG_HOME/conda/condarc.yaml
# New-Item -ItemType SymbolicLink -Path ~\.condarc -Target ~\.dotfiles\.config\conda\condarc.yaml
#  ln -s $DOTFILES/.config/conda/condarc.yaml $XDG_CONFIG_HOME/conda/.condarc
# Reference: https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html
auto_activate_base: false 