fork = false
frame = "full"
idle = true
maximized = false
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false
wsl = true

[font]
normal = [
  "Iosevka Nerd Font",
  "霞鹜文楷等宽",
] # Will use the bundled Fira Code Nerd Font by default
size = 14.0
