# $XDG_CONFIG_HOME/neovide/config.toml
# ln -sf $DOTFILES/mac/neovide.toml $XDG_CONFIG_HOME/neovide/config.toml
# New-Item -ItemType SymbolicLink -Path $Env:XDG_CONFIG_HOME/neovide/config.toml -Value $DOTFILES\mac\neovide.toml (Mac)
# https://neovide.dev/config-file.html?highlight=toml#config-file
# 设置为 fork 默认后台运行，不会占用终端
fork = true
# frame = "full"
idle = true
maximized = false
# neovim-bin = "/opt/homebrew/bin/nvim"
frame = "full"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [
    "Maple Mono NF",
    "Iosevka Nerd Font",
] # Will use the bundled Fira Code Nerd Font by default
size = 14.0
