return {
  "ibhagwan/fzf-lua",
  -- optional for icon support
  dependencies = { "nvim-tree/nvim-web-devicons" },
  cmd = "FzfLua",
  keys = {
    { "<leader><leader>", "<cmd>FzfLua files<CR>",                    desc = "Find Files" },
    { "<leader>fc",       "<cmd>FzfLua files cwd=~/.config/nvim<CR>", desc = "Edit configs" },
    { "<leader>/",        "<cmd>FzfLua live_grep<CR>",                desc = "Grep Files" },
    { "<leader>;",        "<cmd>FzfLua<CR>",                          desc = "Show Telescope Commands" },
    { "<leader>ui",       "<cmd>FzfLua colorschemes<CR>",             desc = "Change colorscheme" },
    -- find_files { "<leader>pp",       "<cmd>FzfLua projects<CR>",                 desc = "Listfind_files  all Projects" },
    { "<leader>pd",       "<cmd>FzfLua zoxide<CR>",                   desc = "List recent directories" },
    -- { "<leader>pg",       "<cmd>FzfLua projects<CR>",                 desc = "List all Git Projects" },
    { "<leader>ps",       "<cmd>FzfLua session-lens<CR>",             desc = "List all sessions" },
    { "<leader>gs",       "<cmd>FzfLua git_status<CR>",               desc = "Git Status" },
    { "<leader>gt",       "<cmd>FzfLua git_branches<CR>",             desc = "Git Branches" },
    { "<leader>gc",       "<cmd>FzfLua git_commits<CR>",              desc = "Show commits" },
    { "<leader>fb",       "<cmd>FzfLua buffers<CR>",                  desc = "List Buffers" },
    { "<leader>ff",       "<cmd>FzfLua fd<CR>",                       desc = "Find Files" },
    { "<leader>fh",       "<cmd>FzfLua oldfiles<CR>",                 desc = "Recent Files" },
    { "<leader>ce",       "<cmd>FzfLua diagnostics<CR>",              desc = "Navigate errors/warnings" },
    { "<leader>cs",       "<cmd>FzfLua treesitter<CR>",               desc = "Search symbols" },
    { "<leader>cS",       "<cmd>FzfLua grep_string<CR>",              desc = "Search current symbol" },
    { "<leader>bB",       "<cmd>FzfLua buffers<CR>",                  desc = "List Buffers" },
    { "<leader>fl",       ":FzfLua filetypes",                        desc = "Set Filetype/Lang to ..." },
    { "<leader>R",        "<cmd>FzfLua resume<CR>",                   desc = "Resume FzfLua" },
  },
  opts = {},
}
