keys:
  - &host_zephyrus age1amkejw3q2aqf8yvh9mkqw8ad4g89mkuudyhv5k6k7s722fa85d6skem8vc
  - &user_js0ny age1mcvqpg39t32ll684r4m2l8j0l9zag6endg0h6zjw8svkgdwc4pjqkk5fvj

creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
        - *user_js0ny
        - *host_zephyrus
