# vim:ft=bash
# If wheel and antidots:
# ln -sf $DOTFILES/tools/bash/profile ~/.config/bash/bashrc
# If not wheel or antidots:
# ln -sf $DOTFILES/tools/bash/bashrc ~/.bashrc

export DOTFILES=$HOME/.dotfiles
# Force to choose English font name
export LC_CTYPE=en_GB.UTF-8

if [ -n "$WSL_DISTRO_NAME" ]; then
    alias clip="clip.exe"
    alias paste="pwsh.exe -NoProfile -Command 'Get-Clipboard'"
elif [ -n "$WAYLAND_DISPLAY" ]; then
    alias clip="wl-copy"
    alias paste="wl-paste"
elif [ -n "$DISPLAY" ]; then
    alias clip="xclip"
fi

source "$DOTFILES"/tools/bash/bash_aliases # For compatibility

export IPYTHONDIR="$XDG_CONFIG_HOME"/ipython

if command -v fzf >/dev/null; then
    eval "$(fzf --bash)"
fi

if command -v starship >/dev/null; then
    eval "$(starship init bash)"
fi
#
# bind 'set show-mode-in-prompt off'
