# $DOTFILES/common/glow.yaml
# Date: 2024-12-22
# Author: js0ny

# Location:
# ~/.config/glow/config.yml
# ln -sf $DOTFILES/glow/glow.yaml ~/.config/glow/config.yml
# style name or JSON path (default "auto")
style: "auto"
# mouse support (TUI-mode only)
mouse: true
# use pager to display markdown
pager: true
# word-wrap at width
width: 80
